### ISSUE TITLE
Missing QCustomer class

### ISSUE THREAD

**Issue by nenta** [ralscha/mycustomer#1]
Hi

Can't build this sample app cause missing QCustomer class...
Please add QCustomer class.

Regards

**Comment by ralscha** [comment]
Hi

The Q-classes are generated by an annotation processor. You can clone the project, then call ```mvn compile``` and you find the Q-classes in the directory ```target\generated-sources\java\ch\rasc\mycustomer\entity```

**Comment by nenta** [comment]
Thanks for quick reply :)

Oh! I don't know about the Q-classes generated by Querydsl...
After complied, QCustomer is generated and sample app work successfully . Thank you for your advice!


BTW,  sample Ext JS project `client` generated by Sencha Cmd 6.0.3.46.
I can't find this Cmd version in Sencha support site...
I'd appreciate it if you could upgrade project Cmd version to stable version.

Be careful when upgrade version to 6.1.2.15, I got error cause `client/workspace.json`.
This file should have `frameworks` property, but don't have. maybe Cmd 6.0.3.46 bug...

Regards.
