### ISSUE TITLE
missing ch.rasc.mycustomer.entity.QCustomer

### ISSUE THREAD

**Issue by halflife3** [ralscha/mycustomer#2]
hi, your project is missing ch.rasc.mycustomer.entity.QCustomer

**Comment by ralscha** [comment]
The Q-classes are generated by an annotation processor. After you cloned the project, call ```mvn compile``` in the command prompt and you find the Q-classes in the directory target\generated-sources\java\ch\rasc\mycustomer\entity

**Comment by halflife3** [comment]
thanks 
and sorry for this duplicate issue

**Comment by ralscha** [comment]
No problem. I get this question a lot and I know it's a bit confusing especially when people just starting with all of this. 
The Q-classes are used by QueryDsl for creating type safe queries. You find more information about QueryDsl on the homepage: http://www.querydsl.com/
