### ISSUE TITLE
get ERR UNKNOWN COMMAND ON sencha install

### ISSUE THREAD

**Issue by wgoldman1** [ralscha/mycustomer#4]
C:\gitsb\mycustomer>sencha install --framework=\tools\Sencha\
Sencha Cmd v6.1.2.15
[ERR] Unknown command: "install"

C:\gitsb\mycustomer>sencha install --framework=/tools/Sencha/
Sencha Cmd v6.1.2.15
[ERR] Unknown command: "install"

**Comment by ralscha** [comment]
You are using an old Sencha Cmd.     
It should work with the latest version:  Sencha Cmd v6.6.x

**Comment by wgoldman1** [comment]
\mycustomer\clientopen>npm install
npm ERR! code E403
npm ERR! 403 Forbidden: @sencha/ext-charts@^6.6.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TEST\AppData\Roaming\npm-cache\_logs\2019-01-21T13_03_32_411Z-debug.log

log has (and others)...
1256 http fetch GET 403 https://npm.sencha.com/@sencha%2fext-charts 1250ms
1257 silly fetchPackageMetaData error for @sencha/ext-charts@^6.6.0 403 Forbidden: @sencha/ext-charts@^6.6.0

**Comment by wgoldman1** [comment]
also tried the following from ...\mycustomer\clientopen

npm install
npm ERR! code E403
npm ERR! 403 Forbidden: @sencha/ext-modern-theme-material@6.6.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TEST\AppData\Roaming\npm-cache\_logs\2019-01-21T13_34_11_227Z-debug.log

**Comment by ralscha** [comment]
You need to login with your Sencha account first. See the prerequisites section in the readme
```
npm login --registry=https://npm.sencha.com --scope=@sencha
```

**Comment by wgoldman1** [comment]
yep, did that, got the sencha account
username: warren..goldman
password: ....

**Comment by ralscha** [comment]
Okay. In that case your account does not have the privileges to access `ext-modern-theme-material`.
Do you know that type of account you have and what packages you can access?

**Comment by wgoldman1** [comment]
No, just asked for a free tutorial one....

**Comment by ralscha** [comment]
Is this a trial account 
https://www.sencha.com/products/evaluate/

or a community edition account     
https://www.sencha.com/products/extjs/communityedition/

**Comment by wgoldman1** [comment]
guessing trial this was also in the email

Thanks for Requesting a Trial of Ext JS 6.6

**Comment by ralscha** [comment]
Would be interesting to know what the Trial account entails.

**Comment by wgoldman1** [comment]
should I try the community one?

**Comment by wgoldman1** [comment]
the email paragraph (see above) implies pretty much everything:
Ext JS and all related packages are hosted on Sencha’s private npm registry. Follow the steps in the Getting Started Guide to build your first Ext JS application.

**Comment by ralscha** [comment]
You are right. It looks like as if you have access to everything. 
Ask the Sencha support first. Maybe there are some hidden restrictions in place. 

Send this error message to the support, they should be able to tell you what's wrong. 
```
npm ERR! 403 Forbidden: @sencha/ext-modern-theme-material@6.6.0
```

**Comment by wgoldman1** [comment]
k, thx

**Comment by wgoldman1** [comment]
so the login I used was wrong.

\mycustomer\clientopen>npm run dev

> mycustomer@0.0.1 dev C:\pace\gitsb\mycustomer\clientopen
> webpack-dev-server --env.verbose=no --env.environment=development

i [ext]: ext-webpack-plugin v1.0.3, Ext JS v6.6.0.258 Commercial Edition, Sencha Cmd v6.6.0.22, webpack v4.28.4
i [ext]: Building for development
i ｢wds｣: Project is running at http://0.0.0.0:1962/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./
i ｢wds｣: 404s will fallback to /index.html
i [ext]: Building Ext bundle at: ./
i [ext]:  [ERR] Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion' has value '1.8', but '1.6' is required. Error: could not find java.dll Error: could not find Java SE Runtime Environment.
i [ext]: Completed ext-webpack-plugin processing
× ｢wdm｣: Built at: 01/21/2019 3:30:23 PM

ERROR in 2
i ｢wdm｣: Failed to compile.

**Comment by wgoldman1** [comment]
I tried the mvnw thing, the app seemed to come up, but the main page just shows Loading...

**Comment by wgoldman1** [comment]
I already had java installed so I did not install another per above (do I nned to do that?)
\mycustomer\clientopen>java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by wgoldman1** [comment]
getting a 404 on http://localhost:1962/generatedFiles/bootstrap.js

**Comment by wgoldman1** [comment]
not sure what to do now, tried updating my java, it could not remove java6, I used windows utility to remove java6 (seemed to work fine). I uninstalled node, removed the repo and started over.
all settings I can find with the windows utility referencing java6 are gone, however, the npm run dev is picking it up from somewhere (even though I have uninstalled node and reinstalled)

gitsb\mycustomer\clientopen
> webpack-dev-server --env.verbose=no --env.environment=development

i [ext]: ext-webpack-plugin v1.0.3, Ext JS v6.6.0.258 Commercial Edition, Sencha Cmd v6.6.0.22, webpack v4.28.4
i [ext]: Building for development
i ｢wds｣: Project is running at http://0.0.0.0:1962/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./
i ｢wds｣: 404s will fallback to /index.html
i [ext]: Building Ext bundle at: ./
i [ext]:  [ERR] Error: could not open `C:\pace\tools\Java\jre6\lib\amd64\jvm.cfg'
i [ext]: Completed ext-webpack-plugin processing
× ｢wdm｣: Built at: 01/21/2019 4:58:28 PM

ERROR in 1
i ｢wdm｣: Failed to compile.

not sure what to do...

**Comment by wgoldman1** [comment]
Oh joy! I think I may have it. Had to delete java.exe from window\system32 folder. Bizarro. Thanks for all your help, btw. Sorry to be such a bother.

**Comment by ralscha** [comment]
No problem. Glad to hear that it works now.
